version: '3'

networks:
  app-tier:
    external: true

services:
  motion-detection-server:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8999:8999
      - 9229:9229
    command: npm start
    networks:
        - app-tier