version: '3'

networks:
  app-tier:
    external: true

services:
  motion-detection-webapp:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8081:80
    networks:
        - app-tier
